services:
  e5-renewal:
    build: .
    container_name: e5-renewal
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/app/config.yaml:ro
      - ./data:/app/data
    # environment:
    #   - E5_PATH_PREFIX=/e5
